removing this test due to
(virtualenv) adking@soko04:~/test_dir/49455$ teuthology-suite -k distro --email adking@redhat.com --machine-type trial --suite orch/cephadm --priority 80 --ceph wip-adk3-testing-2026-02-19-2000 --teuthology-branch main --limit 100 --subset 1/20 --dry-run
2026-02-21 18:52:57,907.907 INFO:teuthology.suite:Using random seed=396
2026-02-21 18:52:57,908.908 INFO:teuthology.suite.run:Checking for expiration (None)
2026-02-21 18:52:57,908.908 INFO:teuthology.suite.run:kernel sha1: distro
2026-02-21 18:52:58,009.009 INFO:teuthology.suite.run:ceph sha1: 40fe9656072005c5f469a2b8ac38bc2b002136b5
2026-02-21 18:52:58,009.009 INFO:teuthology.suite.run:ceph-ci branch: wip-adk3-testing-2026-02-19-2000 40fe9656072005c5f469a2b8ac38bc2b002136b5
2026-02-21 18:52:58,014.014 INFO:teuthology.repo_utils:Cloning https://git.ceph.com/ceph-ci.git wip-adk3-testing-2026-02-19-2000 from upstream
2026-02-21 18:53:51,227.227 INFO:teuthology.suite.run:teuthology branch: main fa17720d0088c3ac28e473468bfc79eeaff5cd38
2026-02-21 18:53:51,333.333 INFO:teuthology.suite.build_matrix:Subset=1/20
2026-02-21 18:53:51,393.393 INFO:teuthology.suite.run:Suite orch:cephadm in /tank/home/adking/src/git.ceph.com_ceph-c_40fe9656072005c5f469a2b8ac38bc2b002136b5/qa/suites/orch/cephadm generated 118 jobs (not yet filtered or merged)
Traceback (most recent call last):
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/bin/teuthology-suite", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/scripts/suite.py", line 232, in main
    return teuthology.suite.main(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/teuthology/suite/__init__.py", line 140, in main
    run.prepare_and_schedule()
  File "/tank/home/adking/teuth-venv/teuthology/teuthology/suite/run.py", line 467, in prepare_and_schedule
    num_jobs = self.schedule_suite()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/teuthology/suite/run.py", line 636, in schedule_suite
    configs = list(config_merge(configs, **config_merge_kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/teuthology/suite/merge.py", line 139, in config_merge
    yaml_cache[path] = (txt, yaml.safe_load(txt))
                             ^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/tank/home/adking/teuth-venv/teuthology/virtualenv/lib/python3.12/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 62, column 1:
    basicConstraints=CA:FALSE
    ^
could not find expected ':'
  in "<unicode string>", line 63, column 1:
    keyUsage=digitalSignature,keyEnc ...
    ^